import type { Metadata } from 'next';
import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/shared/ui/utils';
import { AppProvider } from './_providers/app-provider';
import 'reactflow/dist/style.css';

export const metadata: Metadata = {
  title: 'Courses', // Заголовок страницы
  description: 'Generated by create next app', // Описание страницы
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Элемент html с указанием языка 'ru' и подавлением предупреждения о гидратации
    <html lang="ru" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased flex flex-col',
          fontSans.variable
        )}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
